dist: trusty
INSTALL_NODE_AND_WASM: &INSTALL_NODE_AND_WASM
  |
    rustup target add wasm32-unknown-unknown
    cargo install wasm-pack
    curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh | bash
    source ~/.nvm/nvm.sh
    nvm install v8.11
language: rust
cache:
  cargo: true
  yarn: true
  directories:
    - node_modules
    - .git/lfs
notifications:
  email: false
git:
  lfs_skip_smudge: true
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  local_dir: packages/image/demo
  on:
    branch: master
rust:
  - beta
install:
  - *INSTALL_NODE_AND_WASM
  - git lfs pull
  - npm install -g yarn coveralls nyc @patrickhulce/scripts lerna@3.x
  - yarn install --check-files
script:
  - export PKG_TARGET="node8-linux"
  - npm run build
  - npm run test:lint
  - npm run test:coverage
after_success:
  - nyc report --reporter=text-lcov | coveralls || echo 'Failed to upload to coveralls...'
  - ./scripts/publish.sh
