dist: trusty
language: node_js
cache: yarn
notifications:
  email: false
node_js:
  - "8"
  - "7"
  - "6"
install:
  - yarn install --check-files
script:
  - export PKG_TARGET="node${TRAVIS_NODE_VERSION}-linux"
  - npm run build
  - npm run test:lint
  - npm run test:unit
