dist: trusty
language: node_js
cache:
  yarn: true
  directories:
    - test/fixtures/
notifications:
  email: false
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  local_dir: demo
  on:
    branch: master
node_js:
  - v7
  - v6
before_install:
  - npm install -g coveralls nyc
install:
  - yarn install --check-files
script:
  - npm run build
  - npm run test:lint
  - npm run test:download
  - LOOSE_COMPARISON_TOLERANCE=15 npm run test:coverage
after_success:
  - nyc report --reporter=text-lcov | coveralls || echo 'Failed to upload to coveralls...'
  # - npm run semantic-release
