dist: trusty
language: node_js
cache:
  yarn: true
  directories:
    - node_modules
    - .git/lfs
notifications:
  email: false
git:
  lfs_skip_smudge: true
node_js:
  - v8
  - v6
install:
  - git lfs pull
  - npm install -g coveralls nyc
  - yarn install --check-files
script:
  - export PKG_TARGET="node${TRAVIS_NODE_VERSION}-linux"
  - npm run build
  - npm run test:lint
  - npm run test:coverage
after_success:
  - nyc report --reporter=text-lcov | coveralls || echo 'Failed to upload to coveralls...'
