stages:
  - build
  - test
  - name: deploy
    if: branch = master
jobs:
  include:
    - stage: build
      os: osx
      language: node_js
      node_js: v8
      script: npm run build
      env: PKG_TARGET=node8-mac
    - stage: build
      os: linux
      dist: trusty
      language: node_js
      node_js: v8
      script: npm run build
      env: PKG_TARGET=node8-linux
    - stage: test
      os: linux
      dist: trusty
      language: rust
      rust:
        - beta
      env: PKG_TARGET=node8-linux ENABLE_WASM=1
      script:
        - npm run build
        - npm run test:lint
        - npm run test:coverage
        - nyc report --reporter=text-lcov | coveralls || echo 'Failed to upload to coveralls...'
    - stage: deploy
      os: linux
      dist: trusty
      language: node_js
      node_js: v8
      script:
        - npm run build
        - ./scripts/publish.sh
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GH_TOKEN
        local_dir: packages/image/demo
cache:
  cargo: true
  yarn: true
  directories:
    - node_modules
    - .git/lfs
notifications:
  email: false
git:
  lfs_skip_smudge: true
install:
  - ./scripts/install-node-and-wasm.sh
  - git lfs pull
  - npm install -g yarn coveralls nyc @patrickhulce/scripts
  - yarn install --check-files
