dist: trusty
language: node_js
cache:
  yarn: true
  directories:
    - test/fixtures/
notifications:
  email: false
node_js:
  - v7
  - v6
before_install:
  - npm install -g coveralls nyc
script:
  - npm run build
  - npm run test:lint
  - npm run test:download
  - npm run test:coverage
after_success:
  - nyc report --reporter=text-lcov | coveralls || echo 'Failed to upload to coveralls...'
  - npm run semantic-release
