dist: trusty
language: node_js
cache: yarn
notifications:
  email: false
node_js:
  - v8
  - v7
  - v6
before_install:
  - npm install -g coveralls nyc
install:
  - yarn install --check-files
script:
  - npm run test:lint
  - PKG_TARGET=node8-linux npm run build
  - npm run test:coverage
after_success:
  - nyc report --reporter=text-lcov | coveralls || echo 'Failed to upload to coveralls...'
  - npm run semantic-release
deploy:
  provider: releases
  api_key:
    secure: R8qrXfEFDlNyOjfOCXWoa52WRGx0lPt8moegnyiQhorps/xqItO+8R2yEjHqHo1MOHxX9uhr4ihjqWdxzykF1peAT9U0MOUs4G6XqinU/3VU9WtHIW+BSZLeiZ7GNLiegg3jfPnjk/d+BKM2f0ZeFeXFDxGc85yABsl5HunzaqHGh/I1g3a9G76ev2L0kZxEsd14LStITXzTBqFV4HmMV4v8nFWZPS/hI6XmRyuF6vdLoo18Zv/wnVMiDkM3wnyudrlQCgRnIVhVTtnfGN2m3+8fZOlZUpre6DL1F3E7iLTvzBQTt5fAXLZYSnMQWc3qnwO4H1tLgSSwE1WT9fv/6PtYDg41qbmNmXJg0oqTyvLpxhEFRq/OSKm5TWFx/luqOMM4YDRzRsL8XzJWxWhKfg3Qe3LPFMowj8Th575l/6x8vLTZIfhUfbpbtkV89/MYrfyPP5amT22KdDm3qJcRTT+DHdUSznfBNYV0Gc4iIlCuHdGdr51sysMZGedQPFbQfYzqBViuZcfSb47VMVRyKk9LSPyTIpth1z1U6Q6CXKN2jsiI5/EsB2FFt0BBTRxc+6jeqvMThBklRdKNk2CYirsH4nijl6SMQ+72PyHLq5w7hfW1GB5MVMnK9EjZJWy2zQ6oSm3F22ap858uhg7S3jvWanCexuebpTfdufWuZzY=
  file: out/node8-linux.tar.gz
  skip_cleanup: true
  on:
    repo: ouranos-oss/js-image-cli
    tags: true
    node: 8
