name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: '0 12 * * *'
jobs:
  test:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Windows
            os: windows-latest
            pkg-target: node10-win
          - name: macOS
            os: macos-latest
            pkg-target: node10-mac
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: false
      - name: Run git lfs ls-files
        shell: bash
        run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id
      - name: Cache git lfs
        uses: actions/cache@v2
        id: lfs-cache
        with:
          path: .git/lfs
          key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}-v1
          restore-keys: |
            ${{ runner.os }}-lfs-
      - name: Run git lfs pull
        run: git lfs pull && rm .lfs-assets-id
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '10.15.3'
      - name: Patch node-gyp on windows
        if: matrix.os == 'windows-latest'
        shell: powershell
        run: |
          npm install --global node-gyp@latest
          npm prefix -g | % {npm config set node_gyp "$_\node_modules\node-gyp\bin\node-gyp.js"}
      - run: yarn install
      - run: yarn build
        env:
          PKG_TARGET: ${{ matrix.pkg-target }}
      - run: yarn test:lint
        if: matrix.os == 'macos-latest'
      - run: yarn test:unit:ci
  publish:
    name: Publish
    needs: [test]
    runs-on: macos-latest
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    steps:
      - name: Run git context
        id: git
        shell: bash
        run: |
          echo "GITHUB_EXTRA__REFNAME=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          if [[ $GITHUB_REF = refs/heads/* ]]; then echo "GITHUB_EXTRA__BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV ; fi
          if [[ $GITHUB_REF = refs/tags/* ]]; then echo "GITHUB_EXTRA__TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV ; fi
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: false
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '10.15.3'
      - run: yarn install
      - run: yarn build
        env:
          PKG_TARGET: node10-mac
      - run: bash ./scripts/publish.sh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
